stages:
  - deploy

Deploy:
  stage: deploy
  before_script:
    - curl -L https://fly.io/install.sh | sh
    - export FLYCTL_INSTALL="/root/.fly"
    - export PATH="$FLYCTL_INSTALL/bin:$PATH"
  script:
    - flyctl deploy
    - flyctl status
